import {Search,X} from 'lucide-react'
import {useMemo,useState} from 'react'
import {idioms,type Category,type Difficulty} from '../data/idioms'
import {getRecord} from '../store'
import {IdiomCard} from '../components/IdiomCard'
const categories=['易望文生义','褒贬误用','对象误用','语法误用','近义混淆','谦敬误用','其他'] as Category[]
const difficulties=['基础','进阶','高频易错'] as Difficulty[]
const states=[['all','全部'],['unlearned','未学习'],['mastered','已掌握'],['mistake','易错'],['favorite','已收藏']] as const
export function IdiomList(){const [q,setQ]=useState(''),[cat,setCat]=useState<Category|''>(''),[difficulty,setDifficulty]=useState<Difficulty|''>(''),[state,setState]=useState<(typeof states)[number][0]>('all'),[v,setV]=useState(0);const result=useMemo(()=>idioms.filter(i=>{const r=getRecord(i);const text=`${i.title} ${i.meaning} ${i.tags.join(' ')}`.toLowerCase();return(!q||text.includes(q.toLowerCase()))&&(!cat||i.category===cat)&&(!difficulty||i.difficulty===difficulty)&&(state==='all'||state==='favorite'?state==='all'||r.isFavorite:r.status===state)}),[q,cat,difficulty,state,v]);const reset=()=>{setQ('');setCat('');setDifficulty('');setState('all')};return <div><div className="mb-7"><p className="text-sm font-bold text-indigo-600">成语库 · {idioms.length} 条</p><h1 className="display mt-2 text-4xl font-bold text-indigo-950">从误区里，把词记牢</h1></div><div className="paper rounded-2xl p-4 sm:p-5"><label className="relative block"><Search className="absolute left-4 top-3.5 text-slate-400" size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索成语、释义或标签" className="focus-ring w-full rounded-xl border border-slate-200 bg-slate-50 py-3 pl-11 pr-4 outline-none"/></label><div className="mt-4 grid gap-3 sm:grid-cols-2"><select aria-label="按分类筛选" value={cat} onChange={e=>setCat(e.target.value as Category|'')} className="focus-ring rounded-xl border border-slate-200 bg-white p-3"><option value="">全部分类</option>{categories.map(x=><option key={x}>{x}</option>)}</select><select aria-label="按难度筛选" value={difficulty} onChange={e=>setDifficulty(e.target.value as Difficulty|'')} className="focus-ring rounded-xl border border-slate-200 bg-white p-3"><option value="">全部难度</option>{difficulties.map(x=><option key={x}>{x}</option>)}</select></div><div className="mt-4 flex flex-wrap gap-2">{states.map(([key,label])=><button key={key} onClick={()=>setState(key)} className={`focus-ring chip ${state===key?'bg-indigo-700 text-white':'bg-slate-100 text-slate-600'}`}>{label}</button>)}{(q||cat||difficulty||state!=='all')&&<button onClick={reset} className="chip text-slate-500"><X size={14}/>清除筛选</button>}</div></div><div className="my-5 text-sm text-slate-500">找到 <b className="text-indigo-800">{result.length}</b> 条成语</div>{result.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{result.map(i=><IdiomCard key={i.id} idiom={i} onChange={()=>setV(x=>x+1)}/>)}</div>:<div className="paper rounded-2xl py-20 text-center text-slate-500">没有符合条件的成语，换个筛选条件试试。</div>}</div>}
