import { Eye, EyeOff, Pencil, Search, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useMemo, useState } from 'react'
import { useIdioms } from '../../hooks/useIdioms'
import { supabase } from '../../lib/supabase'

export function AdminDashboardPage(){
  const {idioms,loading,error,refresh}=useIdioms(true)
  const [query,setQuery]=useState(''),[category,setCategory]=useState(''),[difficulty,setDifficulty]=useState(''),[visibility,setVisibility]=useState('')
  const categories=useMemo(()=>[...new Set(idioms.map(item=>item.category))],[idioms])
  const filtered=idioms.filter(item=>(!query||`${item.title} ${item.code}`.toLowerCase().includes(query.toLowerCase()))&&(!category||item.category===category)&&(!difficulty||item.difficulty===difficulty)&&(!visibility||String(item.is_visible)===visibility))
  const recent=[...idioms].sort((a,b)=>b.updated_at.localeCompare(a.updated_at)).slice(0,5)
  const toggle=async(id:string,value:boolean)=>{if(!supabase)return;await supabase.from('idioms').update({is_visible:value}).eq('id',id);await refresh()}
  const remove=async(id:string,title:string)=>{if(!supabase||!window.confirm(`确定删除“${title}”吗？公开例句和用户学习记录也会一并删除。`))return;const {error}=await supabase.from('idioms').delete().eq('id',id);if(error)window.alert(error.message);await refresh()}
  return <div className="min-w-0"><h1 className="text-2xl font-bold text-indigo-950">内容管理</h1><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{[[idioms.length,'成语总数'],[idioms.filter(x=>x.is_visible).length,'已展示'],[idioms.filter(x=>!x.is_visible).length,'已隐藏'],[idioms.filter(x=>x.difficulty==='高频易错').length,'高难度']].map(([value,label])=><div key={String(label)} className="paper min-w-0 rounded-2xl p-4 sm:p-5"><strong className="text-2xl text-indigo-950 sm:text-3xl">{value}</strong><p className="mt-1 text-sm text-slate-500">{label}</p></div>)}</div>
    <div className="mt-5 grid min-w-0 gap-5 sm:mt-6 lg:grid-cols-[minmax(0,1fr)_280px]"><section className="paper min-w-0 overflow-hidden rounded-2xl"><div className="border-b border-slate-100 p-4"><div className="relative"><Search className="absolute left-3 top-3.5 text-slate-400" size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索成语或编号" className="focus-ring min-h-11 w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-3"/></div><div className="mt-3 grid gap-2 sm:grid-cols-3"><select value={category} onChange={e=>setCategory(e.target.value)} className="min-h-11 min-w-0 w-full rounded-lg border border-slate-200 p-2 text-sm"><option value="">全部分类</option>{categories.map(x=><option key={x}>{x}</option>)}</select><select value={difficulty} onChange={e=>setDifficulty(e.target.value)} className="min-h-11 min-w-0 w-full rounded-lg border border-slate-200 p-2 text-sm"><option value="">全部难度</option>{['基础','进阶','高频易错'].map(x=><option key={x}>{x}</option>)}</select><select value={visibility} onChange={e=>setVisibility(e.target.value)} className="min-h-11 min-w-0 w-full rounded-lg border border-slate-200 p-2 text-sm"><option value="">全部状态</option><option value="true">已展示</option><option value="false">已隐藏</option></select></div></div>
      {error&&<p className="break-words p-4 text-sm text-rose-600">{error}</p>}{loading?<p className="p-8 text-center text-slate-500">正在读取…</p>:<div className="divide-y divide-slate-100">{filtered.map(item=><div key={item.id} className="flex min-w-0 flex-col gap-3 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex min-w-0 flex-wrap items-center gap-2"><strong className="break-words text-indigo-950">{item.title}</strong><span className="text-xs text-slate-400">{item.code}</span><span className={`chip ${item.is_visible?'status-mastered':'status-hidden'}`}>{item.is_visible?'展示中':'已隐藏'}</span></div><p className="meta-text mt-1 break-words sm:truncate">{item.category} · {item.difficulty} · 排序 {item.sort_order}</p></div><div className="flex gap-1 self-end sm:self-auto"><Link aria-label="编辑" to={`/admin/idioms/${item.id}/edit`} className="focus-ring flex size-11 items-center justify-center rounded-lg text-indigo-700 hover:bg-indigo-50"><Pencil size={17}/></Link><button aria-label={item.is_visible?'隐藏':'恢复展示'} onClick={()=>void toggle(item.id,!item.is_visible)} className="focus-ring flex size-11 items-center justify-center rounded-lg text-slate-500 hover:bg-slate-100">{item.is_visible?<EyeOff size={17}/>:<Eye size={17}/>}</button><button aria-label="删除" onClick={()=>void remove(item.id,item.title)} className="focus-ring flex size-11 items-center justify-center rounded-lg text-rose-600 hover:bg-rose-50"><Trash2 size={17}/></button></div></div>)}</div>}</section>
      <aside className="paper h-fit min-w-0 rounded-2xl p-4 sm:p-5"><h2 className="font-bold text-slate-800">最近修改</h2><div className="mt-3 space-y-3">{recent.map(item=><Link key={item.id} to={`/admin/idioms/${item.id}/edit`} className="block min-w-0 rounded-xl bg-slate-50 p-3"><strong className="block break-words text-sm text-indigo-950">{item.title}</strong><time className="mt-1 block text-xs text-slate-400">{new Date(item.updated_at).toLocaleString('zh-CN')}</time></Link>)}</div></aside>
    </div></div>
}
