import { ArrowDown, ArrowLeft, ArrowUp, Plus, Save, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useIdioms } from '../../hooks/useIdioms'
import { supabase } from '../../lib/supabase'
import type { Difficulty } from '../../types/database'

interface ExampleDraft { id:string; content:string }
interface FormState {
  code:string; title:string; key_pronunciations:string; pronunciation_note:string; category:string; tags:string; meaning:string; common_mistake:string; applicable_objects:string; common_collocations:string; usage_restrictions:string; difficulty:Difficulty; source:string; is_visible:boolean; sort_order:number
}
const blank:FormState={code:'',title:'',key_pronunciations:'',pronunciation_note:'',category:'其他',tags:'',meaning:'',common_mistake:'',applicable_objects:'',common_collocations:'',usage_restrictions:'',difficulty:'基础',source:'',is_visible:true,sort_order:0}
const temporaryId=()=>`new-${Date.now()}-${Math.random().toString(36).slice(2)}`

export function AdminIdiomFormPage(){
  const {id}=useParams(),navigate=useNavigate(),{idioms,loading}=useIdioms(true)
  const [form,setForm]=useState<FormState>(blank),[examples,setExamples]=useState<ExampleDraft[]>([]),[loadedId,setLoadedId]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('')
  useEffect(()=>{if(!id){if(!loadedId)setLoadedId('new');return}const item=idioms.find(row=>row.id===id);if(item&&loadedId!==id){setForm({code:item.code,title:item.title,key_pronunciations:item.key_pronunciations??'',pronunciation_note:item.pronunciation_note??'',category:item.category,tags:item.tags.join('，'),meaning:item.meaning,common_mistake:item.common_mistake??'',applicable_objects:item.applicable_objects??'',common_collocations:item.common_collocations.join('\n'),usage_restrictions:item.usage_restrictions??'',difficulty:item.difficulty,source:item.source??'',is_visible:item.is_visible,sort_order:item.sort_order});setExamples((item.idiom_examples??[]).map(example=>({id:example.id,content:example.content})));setLoadedId(id)}},[id,idioms,loadedId])
  const field=<K extends keyof FormState>(key:K,value:FormState[K])=>setForm(current=>({...current,[key]:value}))
  const move=(index:number,direction:-1|1)=>{const target=index+direction;if(target<0||target>=examples.length)return;const copy=[...examples];[copy[index],copy[target]]=[copy[target],copy[index]];setExamples(copy)}
  const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!supabase)return;setSaving(true);setError('');try{
    const payload={...form,code:form.code.trim(),title:form.title.trim(),meaning:form.meaning.trim(),tags:form.tags.split(/[，,]/).map(x=>x.trim()).filter(Boolean),common_collocations:form.common_collocations.split('\n').map(x=>x.trim()).filter(Boolean),key_pronunciations:form.key_pronunciations.trim()||null,pronunciation_note:form.pronunciation_note.trim()||null,common_mistake:form.common_mistake.trim()||null,applicable_objects:form.applicable_objects.trim()||null,usage_restrictions:form.usage_restrictions.trim()||null,source:form.source.trim()||null}
    let idiomId=id
    if(id){const {error:updateError}=await supabase.from('idioms').update(payload).eq('id',id);if(updateError)throw updateError}
    else{const {data,error:insertError}=await supabase.from('idioms').insert(payload).select('id').single();if(insertError)throw insertError;idiomId=data.id}
    if(!idiomId)throw new Error('未取得成语 ID')
    const {error:deleteError}=await supabase.from('idiom_examples').delete().eq('idiom_id',idiomId);if(deleteError)throw deleteError
    const rows=examples.map((item,index)=>({idiom_id:idiomId!,content:item.content.trim(),sort_order:index})).filter(item=>item.content)
    if(rows.length){const {error:exampleError}=await supabase.from('idiom_examples').insert(rows);if(exampleError)throw exampleError}
    navigate('/admin')
  }catch(reason){setError(reason instanceof Error?reason.message:'保存失败')}finally{setSaving(false)}}
  if(id&&loading&&!loadedId)return <p className="text-slate-500">正在读取成语…</p>
  return <form onSubmit={event=>void submit(event)}><div className="flex flex-wrap items-center justify-between gap-3"><div><Link to="/admin" className="inline-flex items-center gap-1 text-sm text-slate-500"><ArrowLeft size={15}/>返回管理列表</Link><h1 className="mt-2 text-2xl font-bold text-indigo-950">{id?'编辑成语':'新增成语'}</h1></div><button disabled={saving} className="btn btn-primary"><Save size={17}/>{saving?'正在保存…':'保存成语'}</button></div>{error&&<p className="mt-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}
    <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_300px]"><div className="space-y-5"><section className="paper rounded-2xl p-5 sm:p-7"><h2 className="font-bold text-slate-800">基本信息</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Input label="编号" required value={form.code} onChange={value=>field('code',value)} placeholder="IDM001"/><Input label="成语" required value={form.title} onChange={value=>field('title',value)}/><Input label="主分类" value={form.category} onChange={value=>field('category',value)}/><label className="text-sm font-bold text-slate-700">难度<select value={form.difficulty} onChange={e=>field('difficulty',e.target.value as Difficulty)} className="focus-ring mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal"><option>基础</option><option>进阶</option><option>高频易错</option></select></label><Input label="标签" value={form.tags} onChange={value=>field('tags',value)} placeholder="用逗号分隔"/><Input label="排序值" type="number" value={String(form.sort_order)} onChange={value=>field('sort_order',Number(value))}/><Input label="重点字读音" value={form.key_pronunciations} onChange={value=>field('key_pronunciations',value)} placeholder="刊（kān）"/><Input label="易读错说明" value={form.pronunciation_note} onChange={value=>field('pronunciation_note',value)}/></div></section>
      <section className="paper rounded-2xl p-5 sm:p-7"><h2 className="font-bold text-slate-800">标准知识</h2><div className="mt-5 space-y-4"><Textarea label="准确释义" required value={form.meaning} onChange={value=>field('meaning',value)}/><Textarea label="常见误用" value={form.common_mistake} onChange={value=>field('common_mistake',value)}/><Textarea label="适用对象" value={form.applicable_objects} onChange={value=>field('applicable_objects',value)}/><Textarea label="常见搭配" value={form.common_collocations} onChange={value=>field('common_collocations',value)} hint="每行一条"/><Textarea label="使用限制" value={form.usage_restrictions} onChange={value=>field('usage_restrictions',value)}/><Textarea label="来源或备注" value={form.source} onChange={value=>field('source',value)}/></div></section>
      <section className="paper rounded-2xl p-5 sm:p-7"><div className="flex items-center justify-between"><h2 className="font-bold text-slate-800">标准例句</h2><button type="button" onClick={()=>setExamples([...examples,{id:temporaryId(),content:''}])} className="inline-flex items-center gap-1 text-sm font-bold text-indigo-700"><Plus size={16}/>添加例句</button></div><div className="mt-4 space-y-3">{!examples.length&&<p className="rounded-xl bg-slate-50 p-5 text-center text-sm text-slate-400">暂无例句</p>}{examples.map((item,index)=><div key={item.id} className="flex items-start gap-2"><span className="mt-3 text-xs text-slate-400">{index+1}</span><textarea value={item.content} onChange={e=>setExamples(examples.map(old=>old.id===item.id?{...old,content:e.target.value}:old))} rows={2} className="focus-ring min-w-0 flex-1 rounded-xl border border-slate-200 p-3"/><div className="grid gap-1"><button type="button" aria-label="上移" onClick={()=>move(index,-1)} className="rounded p-1 text-slate-400"><ArrowUp size={15}/></button><button type="button" aria-label="下移" onClick={()=>move(index,1)} className="rounded p-1 text-slate-400"><ArrowDown size={15}/></button><button type="button" aria-label="删除" onClick={()=>setExamples(examples.filter(old=>old.id!==item.id))} className="rounded p-1 text-rose-500"><Trash2 size={15}/></button></div></div>)}</div></section></div>
      <aside><div className="paper sticky top-5 rounded-2xl p-5"><h2 className="font-bold text-slate-800">发布设置</h2><label className="mt-4 flex cursor-pointer items-center justify-between rounded-xl bg-slate-50 p-4 text-sm font-bold text-slate-700"><span><span className="block">向访客展示</span><small className="mt-1 block font-normal text-slate-400">关闭后仅管理员可见</small></span><input type="checkbox" checked={form.is_visible} onChange={e=>field('is_visible',e.target.checked)} className="size-5 accent-indigo-700"/></label><p className="mt-4 text-xs leading-5 text-slate-400">保存后会通过 Realtime 更新前台，无需推送代码或重新部署。</p></div></aside>
    </div>
  </form>
}

function Input({label,value,onChange,required=false,type='text',placeholder=''}:{label:string;value:string;onChange:(value:string)=>void;required?:boolean;type?:string;placeholder?:string}){return <label className="text-sm font-bold text-slate-700">{label}<input type={type} required={required} value={value} placeholder={placeholder} onChange={event=>onChange(event.target.value)} className="focus-ring mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal"/></label>}
function Textarea({label,value,onChange,required=false,hint=''}:{label:string;value:string;onChange:(value:string)=>void;required?:boolean;hint?:string}){return <label className="block text-sm font-bold text-slate-700">{label}{hint&&<small className="ml-2 font-normal text-slate-400">{hint}</small>}<textarea required={required} value={value} onChange={event=>onChange(event.target.value)} rows={3} className="focus-ring mt-2 w-full resize-y rounded-xl border border-slate-200 p-3 font-normal leading-7"/></label>}
